name: Deploy

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt-get install libllvm-10-ocaml-dev libllvm10 llvm-10 llvm-10-dev llvm-10-doc llvm-10-examples llvm-10-runtime clang-10 clang-tools-10 clang-10-doc libclang-common-10-dev libclang-10-dev libclang1-10 clang-format-10 python3-clang-10 clangd-10 libclang-cpp10-dev libclang-cpp10
    - name: Misc
      run: |
        whereis clang-cpp
    - name: Build
      run: |
        export PATH=/usr/local/llvm10/lib;$PATH 
        mkdir build
        cd build
        cmake ..
        make
